INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Drei Kameraden', '1936-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Arc de Triomphe', '1945-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Im Westen nichts Neues', '1928-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Der schwarze Obelisk', '1956-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Geborgtes Leben/Der Himmel kennt keine Günstlinge', '1961-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Die Traumbude', '1920-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Die Nacht von Lissabon', '1961-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (1, 'Liebe Deinen Nächsten', '1941-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (2, 'The Old Man And The Sea', '1952-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (2, 'For Whom the Bell Tolls', '1940-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (2, 'A Farewell to Arms', '1929-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (2, 'The Snows of Kilimanjaro', '1936-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (2, 'Across the River and into the Trees', '1950-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (3, 'Robinson Crusoe', '1719-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (4, 'Fahrenheit 451', '1951-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (4, 'A Sound of Thunder', '1952-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (4, 'Death Is a Lonely Business', '1985-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (4, 'Dandelion Wine', '1957-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (5, 'Le Petit Prince', '1942-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (5, 'Pilote de guerre', '1942-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (5, 'Citadelle', '1944-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (6, 'White Fang', '1906-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (6, 'The Sea-Wolf', '1904-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (6, 'Hearts of Three', '1920-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (6, 'The People of the Abyss', '1903-01-01');
INSERT INTO literature.book (author_id, title, year_of_writing) VALUES (6, 'The White Silence', '1899-01-01');